/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 存活探针 */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 就绪探针（内容已加载 + DB 可连） */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site Settings */
        get: operations["site_settings_api_v1_site_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/navigation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Site Navigation */
        get: operations["site_navigation_api_v1_site_navigation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home_api_v1_home_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products Overview */
        get: operations["products_overview_api_v1_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Products Deployment */
        get: operations["products_deployment_api_v1_products_deployment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product Detail */
        get: operations["product_detail_api_v1_products__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solutions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solutions Overview */
        get: operations["solutions_overview_api_v1_solutions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solutions/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Solution Detail */
        get: operations["solution_detail_api_v1_solutions__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/pillars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Pillars */
        get: operations["research_pillars_api_v1_research_pillars_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/papers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Research Papers */
        get: operations["research_papers_api_v1_research_papers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/about": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About */
        get: operations["about_api_v1_about_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/about/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About Team */
        get: operations["about_team_api_v1_about_team_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/about/careers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** About Careers */
        get: operations["about_careers_api_v1_about_careers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insights */
        get: operations["insights_api_v1_insights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/insights/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Insight Detail */
        get: operations["insight_detail_api_v1_insights__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media Manifest */
        get: operations["media_manifest_api_v1_media_manifest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media Asset */
        get: operations["media_asset_api_v1_media_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 站点路由清单（供 sitemap 与路由回归用）
         * @description 把「有哪些页面」这件事也收敛到后端，让 sitemap.ts 与 routes.spec.ts 同源。
         */
        get: operations["site_routes_api_v1_site_routes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 线索管理列表（需 X-Admin-Token） */
        get: operations["list_leads_api_v1_leads_get"];
        put?: never;
        /** 提交线索 */
        post: operations["create_lead_api_v1_leads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/leads/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 线索 CSV 导出（需 X-Admin-Token） */
        get: operations["export_leads_api_v1_leads_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AboutPage */
        AboutPage: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Lead */
            lead: string;
            /** Heromedia */
            heroMedia?: string | null;
            /** Intro */
            intro: string;
            /**
             * Facts
             * @default []
             */
            facts: components["schemas"]["CompanyFact"][];
            /** Focus */
            focus: string;
            /** Positioningtitle */
            positioningTitle: string;
            /** Positioninglead */
            positioningLead: string;
            /** Positioningbody */
            positioningBody: string;
            /**
             * Tiers
             * @default []
             */
            tiers: components["schemas"]["ProductTierBrief"][];
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["Metric"][];
            /** Strengthtitle */
            strengthTitle: string;
            /** Strengthlead */
            strengthLead: string;
            /**
             * Strength
             * @default []
             */
            strength: components["schemas"]["FeatureItem"][];
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** CareersPage */
        CareersPage: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Lead */
            lead: string;
            /** Heromedia */
            heroMedia?: string | null;
            /**
             * Why
             * @default []
             */
            why: components["schemas"]["FeatureItem"][];
            /**
             * Openings
             * @default []
             */
            openings: components["schemas"]["FeatureItem"][];
            /**
             * Process
             * @default []
             */
            process: string[];
            /** Contactnote */
            contactNote: string;
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** CaseMetric */
        CaseMetric: {
            /**
             * Value
             * @description 头条数字，如 "20+" / "全国第 1"
             */
            value: string;
            /**
             * Unit
             * @description ref 中 .unit 小字
             */
            unit?: string | null;
            /** Label */
            label: string;
            /**
             * Note
             * @description 归属说明。首页 .metrics 场景下必填并实际渲染（spec §3.2 合规约束）
             */
            note?: string | null;
            /**
             * Source
             * @description 内容溯源，如 "PPT p.93"
             */
            source?: string | null;
            /**
             * Before
             * @description 对照基线，如 "原 3.5 小时/份"
             */
            before?: string | null;
        };
        /** CompanyFact */
        CompanyFact: {
            /** Label */
            label: string;
            /** Body */
            body: string;
        };
        /** ContactInfo */
        ContactInfo: {
            /** Businessemail */
            businessEmail: string;
            /** Careersemail */
            careersEmail: string;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** Workinghours */
            workingHours?: string | null;
        };
        /** CtaBlock */
        CtaBlock: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Primarylabel */
            primaryLabel: string;
            /** Primaryhref */
            primaryHref: string;
            /** Secondarylabel */
            secondaryLabel?: string | null;
            /** Secondaryhref */
            secondaryHref?: string | null;
        };
        /** DeliveryForm */
        DeliveryForm: {
            /**
             * Index
             * @description Ⅰ / Ⅱ / Ⅲ
             */
            index: string;
            /** Name */
            name: string;
            /** Points */
            points: string[];
            /**
             * Fit
             * @description 适用场景
             */
            fit: string;
            /** Media */
            media?: string | null;
        };
        /** DeploymentPage */
        DeploymentPage: {
            /** Title */
            title: string;
            /** Lead */
            lead: string;
            /** Eyebrow */
            eyebrow: string;
            /** Heromedia */
            heroMedia?: string | null;
            /**
             * Policy
             * @description 政策与合规 · 准入门槛
             */
            policy?: components["schemas"]["FeatureItem"][];
            /**
             * Readiness
             * @description 技术前提 · 已经具备
             */
            readiness?: components["schemas"]["FeatureItem"][];
            /**
             * Forms
             * @default []
             */
            forms: components["schemas"]["DeliveryForm"][];
            /** Conclusion */
            conclusion: string;
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** DomainCard */
        DomainCard: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Titleen */
            titleEn: string;
            /** Description */
            description: string;
            /** Href */
            href: string;
            /** Media */
            media?: string | null;
            /**
             * Photoclass
             * @description ref 的 .domain-photo-a/-b/-c/-d
             */
            photoClass: string;
        };
        /** FeatureGroup */
        FeatureGroup: {
            /** Title */
            title: string;
            /**
             * Countlabel
             * @description 如 "2 项"
             */
            countLabel?: string | null;
            /** Items */
            items: components["schemas"]["FeatureItem"][];
        };
        /** FeatureItem */
        FeatureItem: {
            /**
             * Index
             * @description 序号，如 "01"
             */
            index: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Icon */
            icon?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeroBlock */
        HeroBlock: {
            /** Eyebrow */
            eyebrow: string;
            /**
             * Titlelead
             * @description ref: 「以智能之眼」
             */
            titleLead: string;
            /**
             * Titleprefix
             * @description ref: 「守」
             */
            titlePrefix: string;
            /**
             * Titleem
             * @description ref: 「数字之安」，渲染为 .em
             */
            titleEm: string;
            /** Subtitle */
            subtitle: string;
            primary: components["schemas"]["LinkItem"];
            secondary: components["schemas"]["LinkItem"];
            /** Media */
            media?: string | null;
        };
        /**
         * HomeMetric
         * @description 首页头条数字。``note`` 必填 —— 见 spec §3.2「第三个指标的合规约束」。
         *
         *     PPT p.93 的「全国第 1」是**西安电子科技大学**的学科评估结果，不是本公司排名。
         *     把它与「20+ 博士硕士」并列且不加说明，会触及《广告法》第九条与第二十八条。
         *     因此 schema 层强制 note 必填，页面上以 --ink-2 / 12px 实际渲染。
         */
        HomeMetric: {
            /**
             * Value
             * @description 头条数字，如 "20+" / "全国第 1"
             */
            value: string;
            /**
             * Unit
             * @description ref 中 .unit 小字
             */
            unit?: string | null;
            /** Label */
            label: string;
            /** Note */
            note: string;
            /**
             * Source
             * @description 内容溯源，如 "PPT p.93"
             */
            source?: string | null;
        };
        /** HomePage */
        HomePage: {
            hero: components["schemas"]["HeroBlock"];
            /** Domainseyebrow */
            domainsEyebrow: string;
            /** Domainstitlelead */
            domainsTitleLead: string;
            /** Domainstitleem */
            domainsTitleEm: string;
            /** Domainsdesc */
            domainsDesc: string;
            domainsMore: components["schemas"]["LinkItem"];
            /** Domains */
            domains: components["schemas"]["DomainCard"][];
            /** Solutionseyebrow */
            solutionsEyebrow: string;
            /** Solutionstitlelead */
            solutionsTitleLead: string;
            /** Solutionstitleem */
            solutionsTitleEm: string;
            /**
             * Solutionstitletail
             * @default
             */
            solutionsTitleTail: string;
            /** Solutionsdesc */
            solutionsDesc: string;
            /** Solutions */
            solutions: components["schemas"]["SolutionRow"][];
            /** Philosophyeyebrow */
            philosophyEyebrow: string;
            /**
             * Philosophytitle
             * @description 分段标题。em=true 的段渲染为 ref 的 .section-title .em，不使用 dangerouslySetInnerHTML
             */
            philosophyTitle: components["schemas"]["TitleSegment"][];
            /** Philosophydesc */
            philosophyDesc: string;
            /** Values */
            values: components["schemas"]["ValueCard"][];
            /** Metrics */
            metrics: components["schemas"]["HomeMetric"][];
            /** Newseyebrow */
            newsEyebrow: string;
            /** Newstitlelead */
            newsTitleLead: string;
            /** Newstitleem */
            newsTitleEm: string;
            /** Newsdesc */
            newsDesc: string;
            newsMore: components["schemas"]["LinkItem"];
            /**
             * Insightspreview
             * @default []
             */
            insightsPreview: components["schemas"]["InsightSummary"][];
            sustain: components["schemas"]["SustainBlock"];
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** InsightDetail */
        InsightDetail: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "insight" | "news" | "research";
            /** Categorylabel */
            categoryLabel: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Publishedat
             * Format: date
             */
            publishedAt: string;
            /**
             * Readingminutes
             * @default 5
             */
            readingMinutes: number;
            /** Heromedia */
            heroMedia?: string | null;
            /** Href */
            href: string;
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
            /**
             * Bodyhtml
             * @description Markdown 渲染并经 bleach 白名单净化后的 HTML
             */
            bodyHtml: string;
            /**
             * Sources
             * @description 资料来源，逐条来自 PPT 标注
             */
            sources?: string[];
        };
        /** InsightSummary */
        InsightSummary: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /**
             * Category
             * @enum {string}
             */
            category: "insight" | "news" | "research";
            /** Categorylabel */
            categoryLabel: string;
            /** Excerpt */
            excerpt: string;
            /**
             * Publishedat
             * Format: date
             */
            publishedAt: string;
            /**
             * Readingminutes
             * @default 5
             */
            readingMinutes: number;
            /** Heromedia */
            heroMedia?: string | null;
            /** Href */
            href: string;
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** LeadCreate */
        LeadCreate: {
            /** Name */
            name: string;
            /** Company */
            company: string;
            /** Title */
            title?: string | null;
            /** Phone */
            phone: string;
            /** Email */
            email?: string | null;
            /**
             * Intent
             * @enum {string}
             */
            intent: "demo" | "consult" | "trial" | "partner" | "career";
            /** Product */
            product?: ("aragonteam" | "inkclaw" | "legallens" | "platform") | null;
            /** Message */
            message?: string | null;
            /** Consent */
            consent: boolean;
            /**
             * Website
             * @description honeypot：非空即视为机器人
             * @default
             */
            website: string;
            /** Sourcepath */
            sourcePath?: string | null;
            /** Utm */
            utm?: {
                [key: string]: string;
            } | null;
        };
        /** LeadCreated */
        LeadCreated: {
            /** Id */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Duplicate
             * @description L4 幂等：10 分钟内的重复提交返回首次的 id，不产生重复线索
             * @default false
             */
            duplicate: boolean;
        };
        /** LeadRead */
        LeadRead: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Company */
            company: string;
            /** Title */
            title?: string | null;
            /**
             * Phone
             * @description 已脱敏：138****0000
             */
            phone: string;
            /**
             * Email
             * @description 已脱敏：z***@example.com
             */
            email?: string | null;
            /**
             * Intent
             * @enum {string}
             */
            intent: "demo" | "consult" | "trial" | "partner" | "career";
            /** Intentlabel */
            intentLabel: string;
            /** Product */
            product?: ("aragonteam" | "inkclaw" | "legallens" | "platform") | null;
            /** Message */
            message?: string | null;
            /** Sourcepath */
            sourcePath?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "new" | "contacted" | "qualified" | "closed";
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** LinkItem */
        LinkItem: {
            /** Label */
            label: string;
            /** Href */
            href: string;
            /**
             * External
             * @default false
             */
            external: boolean;
            /**
             * Note
             * @description ref 中 .submenu a .ext 的小字
             */
            note?: string | null;
        };
        /**
         * LocalizedText
         * @description 为 v2 英文站预留的本地化文本。
         *
         *     v1 只填 ``zh``；``en`` 留空。使用位置见 ``ProductDetail.tagline_i18n`` 等
         *     带 ``_i18n`` 后缀的字段（spec P2-3：不能只定义不使用）。
         */
        LocalizedText: {
            /** Zh */
            zh: string;
            /** En */
            en?: string | null;
        };
        /** Metric */
        Metric: {
            /**
             * Value
             * @description 头条数字，如 "20+" / "全国第 1"
             */
            value: string;
            /**
             * Unit
             * @description ref 中 .unit 小字
             */
            unit?: string | null;
            /** Label */
            label: string;
            /**
             * Note
             * @description 归属说明。首页 .metrics 场景下必填并实际渲染（spec §3.2 合规约束）
             */
            note?: string | null;
            /**
             * Source
             * @description 内容溯源，如 "PPT p.93"
             */
            source?: string | null;
        };
        /** NavGroup */
        NavGroup: {
            /** Label */
            label: string;
            /**
             * Href
             * @description 主菜单项自身是否可点击。为 None 时只作为下拉容器（spec P2-6）
             */
            href?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["LinkItem"][];
        };
        /** Navigation */
        Navigation: {
            /**
             * Utilityleft
             * @default []
             */
            utilityLeft: components["schemas"]["LinkItem"][];
            /**
             * Utilityright
             * @default []
             */
            utilityRight: components["schemas"]["LinkItem"][];
            /**
             * Main
             * @default []
             */
            main: components["schemas"]["NavGroup"][];
            cta: components["schemas"]["LinkItem"];
            /**
             * Footercolumns
             * @default []
             */
            footerColumns: components["schemas"]["NavGroup"][];
            /**
             * Footerlegal
             * @default []
             */
            footerLegal: components["schemas"]["LinkItem"][];
        };
        /** Page[InsightSummary] */
        Page_InsightSummary_: {
            /** Items */
            items: components["schemas"]["InsightSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Hasnext */
            hasNext: boolean;
        };
        /** Page[LeadRead] */
        Page_LeadRead_: {
            /** Items */
            items: components["schemas"]["LeadRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
            /** Hasnext */
            hasNext: boolean;
        };
        /** Paper */
        Paper: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Titleen */
            titleEn: string;
            /**
             * Venue
             * @description "ASE 2026" / "arXiv 预印本"
             */
            venue: string;
            /**
             * Tier
             * @description "CCF-A"
             */
            tier?: string | null;
            /** Summary */
            summary: string;
            /** Problem */
            problem: string;
            /** Method */
            method: string;
            /** Result */
            result: string;
            /**
             * Benchmarks
             * @default []
             */
            benchmarks: string[];
            /**
             * Mapsto
             * @description 对应 TechPillar.id
             */
            mapsTo?: string[];
            /**
             * Products
             * @default []
             */
            products: string[];
            /**
             * Landing
             * @description 落点：支撑产品的哪个模块
             */
            landing?: string | null;
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** PapersPage */
        PapersPage: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Papers */
            papers: components["schemas"]["Paper"][];
            /**
             * Highlights
             * @default []
             */
            highlights: components["schemas"]["Metric"][];
            /** Footnote */
            footnote: string;
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** ProductDetail */
        ProductDetail: {
            /**
             * Slug
             * @enum {string}
             */
            slug: "aragonteam" | "inkclaw" | "legallens";
            /**
             * Tier
             * @enum {string}
             */
            tier: "organization" | "general" | "industry";
            /** Tierlabel */
            tierLabel: string;
            /** Namecn */
            nameCn: string;
            /** Nameen */
            nameEn: string;
            /**
             * Code
             * @description ref .solution-code 样式的产品代号，如 ARA · 01
             */
            code: string;
            /** Tagline */
            tagline: string;
            /** @description v2 英文站预留。v1 只填 zh（spec §2.2 / P2-3） */
            taglineLocalized?: components["schemas"]["LocalizedText"] | null;
            /** Positioning */
            positioning: string;
            /** Heromedia */
            heroMedia?: string | null;
            /**
             * Background
             * @description 四重困境 / 五类风险
             */
            background?: components["schemas"]["FeatureItem"][];
            /**
             * Corevalues
             * @description 五条 / 六条核心价值
             */
            coreValues?: components["schemas"]["FeatureItem"][];
            /**
             * Featuregroups
             * @default []
             */
            featureGroups: components["schemas"]["FeatureGroup"][];
            /**
             * Screens
             * @description 界面导览
             */
            screens?: components["schemas"]["ScreenSection"][];
            /**
             * Highlights
             * @default []
             */
            highlights: components["schemas"]["Metric"][];
            /**
             * Pillars
             * @description TechPillar.id
             */
            pillars?: string[];
            /**
             * Papers
             * @description Paper.id
             */
            papers?: string[];
            /**
             * Delivery
             * @default []
             */
            delivery: string[];
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** ProductSummary */
        ProductSummary: {
            /**
             * Slug
             * @enum {string}
             */
            slug: "aragonteam" | "inkclaw" | "legallens";
            /**
             * Tier
             * @enum {string}
             */
            tier: "organization" | "general" | "industry";
            /** Tierlabel */
            tierLabel: string;
            /** Namecn */
            nameCn: string;
            /** Nameen */
            nameEn: string;
            /** Tagline */
            tagline: string;
            /** Positioning */
            positioning: string;
            /**
             * Audience
             * @description 解决谁的问题
             */
            audience: string;
            /**
             * Differentiator
             * @description 关键差异
             */
            differentiator: string;
            /**
             * Capabilities
             * @description 典型能力
             */
            capabilities?: string[];
            /** Customervalue */
            customerValue: string;
            /**
             * Delivery
             * @description 交付形态
             */
            delivery: string;
            /** Heromedia */
            heroMedia?: string | null;
            /** Href */
            href: string;
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** ProductTierBrief */
        ProductTierBrief: {
            /** Tier */
            tier: string;
            /** Name */
            name: string;
            /** Href */
            href: string;
        };
        /** ProductsOverview */
        ProductsOverview: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Products */
            products: components["schemas"]["ProductSummary"][];
            /** Foundationtitle */
            foundationTitle: string;
            /** Foundationdesc */
            foundationDesc: string;
            /**
             * Foundation
             * @description 四类企业级要件
             */
            foundation?: components["schemas"]["FeatureItem"][];
            /** Footnote */
            footnote: string;
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** ResearchOverview */
        ResearchOverview: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Heromedia */
            heroMedia?: string | null;
            /** Pillars */
            pillars: components["schemas"]["TechPillar"][];
            /**
             * Highlights
             * @default []
             */
            highlights: components["schemas"]["Metric"][];
            /** Footnote */
            footnote: string;
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /**
         * ScreenSection
         * @description 界面导览的一屏：左文右图（或反向）。
         */
        ScreenSection: {
            /** Id */
            id: string;
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Points
             * @default []
             */
            points: string[];
            /** Mediaid */
            mediaId: string;
            /**
             * Layout
             * @default left
             * @enum {string}
             */
            layout: "left" | "right";
            /** Sourceslide */
            sourceSlide?: number | null;
        };
        /** SiteSettings */
        SiteSettings: {
            /** Namecn */
            nameCn: string;
            /** Nameen */
            nameEn: string;
            /** Legalname */
            legalName: string;
            /** Tagline */
            tagline: string;
            /** Description */
            description: string;
            /**
             * Keywords
             * @default []
             */
            keywords: string[];
            contact: components["schemas"]["ContactInfo"];
            /**
             * Icp
             * @description ICP 备案号。为空时页脚不渲染该行（spec R9），上线前由客户填入
             */
            icp?: string | null;
            /** Copyrightyear */
            copyrightYear: number;
            /** Foundednote */
            foundedNote?: string | null;
            /**
             * Pendingconfirmation
             * @description 待客户/法务书面确认的条目（spec §15 / C3），validate_content 会输出告警
             */
            pendingConfirmation?: string[];
        };
        /** SolutionDetail */
        SolutionDetail: {
            /**
             * Slug
             * @enum {string}
             */
            slug: "telecom" | "transportation" | "legal-services" | "finance";
            /** Industry */
            industry: string;
            /** Customer */
            customer: string;
            /** Eyebrow */
            eyebrow: string;
            /** Lead */
            lead: string;
            /** Heromedia */
            heroMedia?: string | null;
            /**
             * Deployment
             * @description 部署形态
             */
            deployment: string;
            /**
             * Scope
             * @description 覆盖范围
             */
            scope?: string[];
            /**
             * Workflow
             * @description 使用方式
             */
            workflow?: string[];
            /**
             * Closure
             * @description 项目闭环 / 复制路径
             */
            closure?: string[];
            /**
             * Closuretitle
             * @default 项目闭环
             */
            closureTitle: string;
            /**
             * Difficulty
             * @description 场景为什么难（p.84）
             */
            difficulty?: string[];
            /**
             * Assets
             * @description 沉淀下来的领域资产（p.84）
             */
            assets?: string[];
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["CaseMetric"][];
            /**
             * Takeaway
             * @description 落地要点
             */
            takeaway: string;
            /** Relatedproduct */
            relatedProduct?: string | null;
            /**
             * Pendingconfirmation
             * @default []
             */
            pendingConfirmation: string[];
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** SolutionRow */
        SolutionRow: {
            /** Id */
            id: string;
            /**
             * Code
             * @description ref .solution-code，如 ARA · 01
             */
            code: string;
            /** Category */
            category: string;
            /** Title */
            title: string;
            /** Titleen */
            titleEn: string;
            /** Description */
            description: string;
            /** Points */
            points: string[];
            primary: components["schemas"]["LinkItem"];
            secondary?: components["schemas"]["LinkItem"] | null;
            /** Media */
            media: string;
            /** Vlabel */
            vlabel: string;
        };
        /** SolutionSummary */
        SolutionSummary: {
            /**
             * Slug
             * @enum {string}
             */
            slug: "telecom" | "transportation" | "legal-services" | "finance";
            /** Industry */
            industry: string;
            /** Customer */
            customer: string;
            /** Summary */
            summary: string;
            /** Deployment */
            deployment: string;
            /** Heromedia */
            heroMedia?: string | null;
            /** Href */
            href: string;
            /**
             * Headlinemetrics
             * @default []
             */
            headlineMetrics: components["schemas"]["CaseMetric"][];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** SolutionsOverview */
        SolutionsOverview: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Partnertitle */
            partnerTitle: string;
            /** Partnername */
            partnerName: string;
            /** Partnerdesc */
            partnerDesc: string;
            /** Solutions */
            solutions: components["schemas"]["SolutionSummary"][];
            /**
             * Method
             * @description 同一套实施方法
             */
            method?: string[];
            /** Footnote */
            footnote: string;
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** SustainBlock */
        SustainBlock: {
            /** Eyebrow */
            eyebrow: string;
            /** Titlelead */
            titleLead: string;
            /** Titleem */
            titleEm: string;
            /** Description */
            description: string;
            /** Points */
            points: components["schemas"]["FeatureItem"][];
            action: components["schemas"]["LinkItem"];
            /** Media */
            media?: string | null;
        };
        /** TeamMember */
        TeamMember: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Degree */
            degree?: string | null;
            /**
             * Bio
             * @default []
             */
            bio: string[];
            /**
             * Highlights
             * @default []
             */
            highlights: string[];
        };
        /** TeamPage */
        TeamPage: {
            /** Eyebrow */
            eyebrow: string;
            /** Title */
            title: string;
            /** Lead */
            lead: string;
            /** Heromedia */
            heroMedia?: string | null;
            /**
             * Origin
             * @description 团队来源与依托（p.88）
             */
            origin?: string[];
            leader: components["schemas"]["TeamMember"];
            /**
             * Leaderroles
             * @description 主要社会兼职（p.90）
             */
            leaderRoles?: string[];
            /**
             * Members
             * @default []
             */
            members: components["schemas"]["TeamMember"][];
            /**
             * Metrics
             * @default []
             */
            metrics: components["schemas"]["Metric"][];
            cta: components["schemas"]["CtaBlock"];
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /** TechPillar */
        TechPillar: {
            /** Id */
            id: string;
            /**
             * Product
             * @enum {string}
             */
            product: "aragonteam" | "inkclaw" | "legallens";
            /** Productlabel */
            productLabel: string;
            /** Title */
            title: string;
            /**
             * Lead
             * @description 一句话导语
             */
            lead: string;
            /**
             * Uncertainty
             * @description 被收敛的不确定性 / 要处理的运行事实
             */
            uncertainty: string;
            /**
             * Uncertaintylabel
             * @default 被收敛的不确定性
             */
            uncertaintyLabel: string;
            /**
             * Mechanism
             * @description 核心机制
             */
            mechanism: string;
            /**
             * Parameters
             * @description 关键设计与工程参数
             */
            parameters?: string[];
            /**
             * Value
             * @description 工程价值
             */
            value: string;
            /**
             * Highlights
             * @default []
             */
            highlights: components["schemas"]["Metric"][];
            /**
             * Media
             * @description MediaAsset.id
             */
            media?: string | null;
            /**
             * Sourceslides
             * @default []
             */
            sourceSlides: number[];
        };
        /**
         * TitleSegment
         * @description 标题片段。``em`` 为真时渲染为 ref 的 ``.section-title .em``（企业主色）。
         */
        TitleSegment: {
            /** Text */
            text: string;
            /**
             * Em
             * @default false
             */
            em: boolean;
            /**
             * Linebreakafter
             * @default false
             */
            lineBreakAfter: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValueCard */
        ValueCard: {
            /**
             * Num
             * @description ref .value-num，如 「01 / 使 命」
             */
            num: string;
            /** Title */
            title: string;
            /** Titleen */
            titleEn: string;
            /** Description */
            description: string;
            /** Quote */
            quote: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    site_settings_api_v1_site_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteSettings"];
                };
            };
        };
    };
    site_navigation_api_v1_site_navigation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Navigation"];
                };
            };
        };
    };
    home_api_v1_home_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomePage"];
                };
            };
        };
    };
    products_overview_api_v1_products_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductsOverview"];
                };
            };
        };
    };
    products_deployment_api_v1_products_deployment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentPage"];
                };
            };
        };
    };
    product_detail_api_v1_products__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "aragonteam" | "inkclaw" | "legallens";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solutions_overview_api_v1_solutions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionsOverview"];
                };
            };
        };
    };
    solution_detail_api_v1_solutions__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: "telecom" | "transportation" | "legal-services" | "finance";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    research_pillars_api_v1_research_pillars_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchOverview"];
                };
            };
        };
    };
    research_papers_api_v1_research_papers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PapersPage"];
                };
            };
        };
    };
    about_api_v1_about_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AboutPage"];
                };
            };
        };
    };
    about_team_api_v1_about_team_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamPage"];
                };
            };
        };
    };
    about_careers_api_v1_about_careers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CareersPage"];
                };
            };
        };
    };
    insights_api_v1_insights_get: {
        parameters: {
            query?: {
                category?: ("insight" | "news" | "research") | null;
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_InsightSummary_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    insight_detail_api_v1_insights__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    media_manifest_api_v1_media_manifest_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    media_asset_api_v1_media_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_routes_api_v1_site_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_leads_api_v1_leads_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                intent?: ("demo" | "consult" | "trial" | "partner" | "career") | null;
                since?: string | null;
            };
            header?: {
                "x-admin-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LeadRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_lead_api_v1_leads_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_leads_api_v1_leads_export_csv_get: {
        parameters: {
            query?: never;
            header?: {
                "x-admin-token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
